apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "skybyte-app.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "skybyte-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "skybyte-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "skybyte-app.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      securityContext:
        seccompProfile:
          type: RuntimeDefault

      containers:
        - name: app

          securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

          capabilities:
            drop:
              - ALL

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: token
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          
    
