apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skybyte-app
spec:
  ingressClassName: traefik

  rules:
    - host: skybyte.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skybyte-app
                port:
                  number: 80
